In [3]:
import pandas as pd
from pyprojroot import here

In [4]:
df = pd.read_csv(here("data/csv/Cancer.csv"))
print(df.shape)
print(df.columns.tolist())
display(df.head(3))

(1500, 9)
['Age', 'Gender', 'BMI', 'Smoking', 'GeneticRisk', 'PhysicalActivity', 'AlcoholIntake', 'CancerHistory', 'Diagnosis']

,Age,Gender,BMI,Smoking,GeneticRisk,PhysicalActivity,AlcoholIntake,CancerHistory,Diagnosis
0,58,1,16.085313,0,1,8.146251,4.148219,1,1
1,71,0,30.828784,0,1,9.361630,3.519683,0,0
2,48,1,38.785084,0,2,5.135179,4.728368,0,1

In [5]:

from langchain_community.utilities import SQLDatabase
from sqlalchemy import create_engine
db_path = str(here("data")) + "/cancer.db"
db_path = f"sqlite:///{db_path}"

engine = create_engine(db_path)
df.to_sql("cancer", engine, index=False)

1500

In [9]:
df = pd.read_csv(here("data/csv/diabetes.csv"))
print(df.shape)
print(df.columns.tolist())
display(df.head(3))

from langchain_community.utilities import SQLDatabase
from sqlalchemy import create_engine
db_path = str(here("data")) + "/diabetes.db"
db_path = f"sqlite:///{db_path}"

engine = create_engine(db_path)
df.to_sql("diabetes", engine, index=False)

(768, 9)
['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1

768

In [6]:
df = pd.read_csv(here("data/csv/heart.csv"))
print(df.shape)
print(df.columns.tolist())
display(df.head(3))

from langchain_community.utilities import SQLDatabase
from sqlalchemy import create_engine
db_path = str(here("data")) + "/heart_disease.db"
db_path = f"sqlite:///{db_path}"

engine = create_engine(db_path)
df.to_sql("heart_disease", engine, index=False)

(1025, 14)
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0

1025